version: '3.8'

services:
  app:
    build: ./container/php
    container_name: app
    restart: always
    ports:
      - 9003:9003
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      TZ: Asia/Tokyo
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

volumes:
  db-data:
    driver: local
